// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/stamplay-js-sdk/stamplay-js-sdk.d.ts
declare namespace Stamplay {

  export interface IStamplayModel {
    signup({}) : any
    new() : IStamplayModel
    get(property : string) : any
    set(property : string, value: any) : void
    unset(property : string) : void
    fetch(id : any) : any
    destroy() : any
    save({}?) : any
    upVote() : any
  }

  export interface IStamplayObject  {
      Model : IStamplayModel
      Collection : any

  }

  export interface StamplayStatic {
      init(appId : string) : void;
      User() : IStamplayObject
      Cobject(object : string) : IStamplayObject
  }
}

declare var Stamplay: Stamplay.StamplayStatic;

declare module "Stamplay" {
    export = Stamplay;
}
